apiVersion: v1
kind: Pod
metadata:
  labels:
    cdk8s.io/metadata.addr: my-chart-my-pod-c8d79087
  name: my-pod
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: main
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
  dnsPolicy: ClusterFirst
  hostNetwork: false
  restartPolicy: Always
  securityContext:
    fsGroupChangePolicy: Always
    runAsNonRoot: true
  setHostnameAsFQDN: false
  terminationGracePeriodSeconds: 30