apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox-test
    cdk8s.io/metadata.addr: my-chart-my-pod-c8d79087
  name: my-busybox-pod
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - command:
        - sh
        - -c
        - sleep infinity
      image: busybox:latest
      imagePullPolicy: Always
      name: main
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
  dnsPolicy: ClusterFirst
  hostNetwork: false
  restartPolicy: Always
  securityContext:
    fsGroup: 65534
    fsGroupChangePolicy: Always
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  setHostnameAsFQDN: false
  terminationGracePeriodSeconds: 30
